/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */ 

package project_gui;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.math.BigInteger;
import java.util.Random;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author arnav
 */
public class project_gui extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form project_gui
     */
    String rsa_privatekey_d="",rsa_publickey_e="",rsa_privatekey_n="",rsa_publickey_n="";
    Random r = new Random();
    BigInteger key_generate = new BigInteger(128,r);
    ArithmeticException ae = new ArithmeticException(); 
    String privkey_path="",pubkey_path="",enc_path="",enc_name="",dec_path="",dec_name="";

    public project_gui() {
        initComponents();
        initialise();
    }
    
    private void initialise(){
        rsa_privatekey_d="";rsa_publickey_e="";rsa_privatekey_n="";rsa_publickey_n="";
        privkey_path="";pubkey_path="";enc_path="";enc_name="";dec_path="";dec_name="";
        int e = 1;
        try
        {
            try (FileReader fr1 = new FileReader("settings.txt")) {
                BufferedReader br1 = new BufferedReader(fr1);
                enc_path=br1.readLine();
                enc_name=br1.readLine();
                dec_path=br1.readLine();
                dec_name=br1.readLine();
                pubkey_path = br1.readLine();
                privkey_path = br1.readLine();
                fr1.close();
            }
            catch(FileNotFoundException ex)
            {
                info("No Settings Found\nPlease Update Settings Before Use");
                e=0;
            }
        }
        catch (IOException rt){info("Technical Problem\nPlease Check The settings.txt File.");}
        
        jTextArea8.setText(enc_path);
        jTextArea9.setText(enc_name);
        jTextArea11.setText(dec_path);
        jTextArea10.setText(dec_name);
        jTextArea12.setText(pubkey_path);
        jTextArea13.setText(privkey_path);
        File file2 = new File(privkey_path+"Private_key.txt");
        try (FileReader fr = new FileReader(file2)) {
            BufferedReader br = new BufferedReader(fr);
            rsa_privatekey_n=br.readLine();
            rsa_privatekey_d=br.readLine();
            fr.close();
        }
        catch(IOException t){info("Inappropriate Private Key.");}
        
        file2 = new File(pubkey_path+"Public_key.txt");
        try (FileReader fr = new FileReader(file2)) {
            BufferedReader br=new BufferedReader(fr);
            rsa_publickey_n=br.readLine();
            rsa_publickey_e=br.readLine();
            fr.close();
        }
        catch(IOException t){info("Inappropriate Public Key.");}
        
        jTextArea1.setText(rsa_privatekey_n+rsa_privatekey_d);
        jTextArea3.setText(rsa_privatekey_n+rsa_privatekey_d);
        jTextArea2.setText(rsa_publickey_n+rsa_publickey_e);
        jTextArea4.setText(rsa_publickey_n+rsa_publickey_e);
    }
    
    private void  info (String i){
        final JFrame f = new JFrame ("NOTE !!!");
        setLocationRelativeTo(null);
        f.setSize(600,600);
        javax.swing.JTextArea ta = new javax.swing.JTextArea("\n\n\n\n\n\n\n\n\n"+i);
        ta.setEditable(false);
        ta.setColumns(100);
        ta.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        ta.setRows(1);
        ta.setAutoscrolls(false);
        f.add(ta);
        f.setVisible(true);
        f.isAlwaysOnTopSupported();
        f.isAlwaysOnTop();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JTabbedPane jTabbedPane1 = new javax.swing.JTabbedPane();
        javax.swing.JLayeredPane jLayeredPane4 = new javax.swing.JLayeredPane();
        javax.swing.JPanel jPanel4 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane10 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jButton5 = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane11 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();
        javax.swing.JScrollPane jScrollPane12 = new javax.swing.JScrollPane();
        jTextArea10 = new javax.swing.JTextArea();
        javax.swing.JScrollPane jScrollPane13 = new javax.swing.JScrollPane();
        jTextArea11 = new javax.swing.JTextArea();
        jButton6 = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane14 = new javax.swing.JScrollPane();
        jTextArea12 = new javax.swing.JTextArea();
        javax.swing.JScrollPane jScrollPane15 = new javax.swing.JScrollPane();
        jTextArea13 = new javax.swing.JTextArea();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        javax.swing.JSeparator jSeparator1 = new javax.swing.JSeparator();
        javax.swing.JSeparator jSeparator2 = new javax.swing.JSeparator();
        jButton10 = new javax.swing.JButton();
        javax.swing.JLabel jLabel7 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel8 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel9 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel10 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel11 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        javax.swing.JLayeredPane jLayeredPane1 = new javax.swing.JLayeredPane();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jButton2 = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        javax.swing.JScrollPane jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jButton4 = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane1 = new javax.swing.JScrollPane();
        jTextPane2 = new javax.swing.JTextPane();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLayeredPane jLayeredPane2 = new javax.swing.JLayeredPane();
        javax.swing.JPanel jPanel3 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        javax.swing.JScrollPane jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        javax.swing.JScrollPane jScrollPane9 = new javax.swing.JScrollPane();
        jTextPane3 = new javax.swing.JTextPane();
        javax.swing.JLabel jLabel6 = new javax.swing.JLabel();
        javax.swing.JLayeredPane jLayeredPane3 = new javax.swing.JLayeredPane();
        javax.swing.JPanel jPanel2 = new javax.swing.JPanel();
        javax.swing.JScrollPane jScrollPane6 = new javax.swing.JScrollPane();
        javax.swing.JTextArea jTextArea7 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("project_gui/Bundle"); // NOI18N
        setTitle(bundle.getString("project_gui.title")); // NOI18N
        setPreferredSize(new java.awt.Dimension(1024, 710));
        setResizable(false);

        jTabbedPane1.setFont(new java.awt.Font("Tunga", 1, 24)); // NOI18N
        jTabbedPane1.setPreferredSize(new java.awt.Dimension(1024, 700));

        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jTextArea8.setRows(1);
        jTextArea8.setAutoscrolls(false);
        jScrollPane10.setViewportView(jTextArea8);

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton5.setText(bundle.getString("project_gui.jButton5.text")); // NOI18N
        jButton5.addActionListener(this);

        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jTextArea9.setRows(1);
        jTextArea9.setAutoscrolls(false);
        jScrollPane11.setViewportView(jTextArea9);

        jTextArea10.setColumns(20);
        jTextArea10.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jTextArea10.setRows(1);
        jTextArea10.setAutoscrolls(false);
        jScrollPane12.setViewportView(jTextArea10);

        jTextArea11.setColumns(20);
        jTextArea11.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jTextArea11.setRows(1);
        jTextArea11.setAutoscrolls(false);
        jScrollPane13.setViewportView(jTextArea11);

        jButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton6.setText(bundle.getString("project_gui.jButton6.text")); // NOI18N
        jButton6.addActionListener(this);

        jTextArea12.setColumns(20);
        jTextArea12.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jTextArea12.setRows(1);
        jTextArea12.setAutoscrolls(false);
        jScrollPane14.setViewportView(jTextArea12);

        jTextArea13.setColumns(20);
        jTextArea13.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jTextArea13.setRows(1);
        jTextArea13.setAutoscrolls(false);
        jScrollPane15.setViewportView(jTextArea13);

        jButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton7.setText(bundle.getString("project_gui.jButton7.text")); // NOI18N
        jButton7.addActionListener(this);

        jButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton8.setText(bundle.getString("project_gui.jButton8.text")); // NOI18N
        jButton8.addActionListener(this);

        jButton9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton9.setText(bundle.getString("project_gui.jButton9.text")); // NOI18N
        jButton9.addActionListener(this);

        jSeparator1.setForeground(new java.awt.Color(255, 0, 0));

        jSeparator2.setForeground(new java.awt.Color(255, 0, 0));

        jButton10.setFont(new java.awt.Font("Stencil", 1, 36)); // NOI18N
        jButton10.setText(bundle.getString("project_gui.jButton10.text")); // NOI18N
        jButton10.setAlignmentY(0.0F);
        jButton10.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        jButton10.addActionListener(this);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel7.setText(bundle.getString("project_gui.jLabel7.text")); // NOI18N

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText(bundle.getString("project_gui.jLabel8.text")); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel9.setText(bundle.getString("project_gui.jLabel9.text")); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel10.setText(bundle.getString("project_gui.jLabel10.text")); // NOI18N

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel11.setText(bundle.getString("project_gui.jLabel11.text")); // NOI18N

        jSeparator3.setForeground(new java.awt.Color(255, 0, 51));

        org.jdesktop.layout.GroupLayout jPanel4Layout = new org.jdesktop.layout.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jSeparator2)
            .add(jSeparator3)
            .add(jSeparator1)
            .add(jPanel4Layout.createSequentialGroup()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jScrollPane12, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                    .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                                .add(jScrollPane10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 560, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                                .add(jScrollPane11, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                            .add(jButton5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                                        .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                                            .add(jScrollPane13, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 560, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                            .add(jButton6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))))
                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel4Layout.createSequentialGroup()
                                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                    .add(jPanel4Layout.createSequentialGroup()
                                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                                            .add(jScrollPane14)
                                            .add(jScrollPane15))
                                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                        .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                                            .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 200, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                                    .add(jLabel11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                                .add(jButton9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))))
                    .add(jButton10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane10)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, jButton5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .add(jLabel7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .add(jLabel8, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jSeparator1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(16, 16, 16)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel9, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane13, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .add(jButton6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane12, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .add(jLabel10, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(18, 18, 18)
                .add(jSeparator2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel11, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jButton7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(jButton8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jScrollPane15, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jButton9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jSeparator3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(17, 17, 17)
                .add(jButton10, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 53, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28))
        );

        org.jdesktop.layout.GroupLayout jLayeredPane4Layout = new org.jdesktop.layout.GroupLayout(jLayeredPane4);
        jLayeredPane4.setLayout(jLayeredPane4Layout);
        jLayeredPane4Layout.setHorizontalGroup(
            jLayeredPane4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane4Layout.setVerticalGroup(
            jLayeredPane4Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane4.setLayer(jPanel4, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab(bundle.getString("project_gui.jLayeredPane4.TabConstraints.tabTitle"), jLayeredPane4); // NOI18N

        jLayeredPane1.setPreferredSize(new java.awt.Dimension(1019, 672));

        jPanel1.setOpaque(false);
        jPanel1.setPreferredSize(new java.awt.Dimension(1019, 740));

        jTextArea3.setEditable(false);
        jTextArea3.setColumns(100);
        jTextArea3.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea3.setRows(1);
        jTextArea3.setAutoscrolls(false);
        jScrollPane3.setViewportView(jTextArea3);

        jButton2.setFont(new java.awt.Font("Shruti", 1, 24)); // NOI18N
        jButton2.setText(bundle.getString("project_gui.jButton2.text")); // NOI18N
        jButton2.addActionListener(this);

        jTextArea4.setEditable(false);
        jTextArea4.setColumns(100);
        jTextArea4.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea4.setRows(1);
        jTextArea4.setAutoscrolls(false);
        jScrollPane4.setViewportView(jTextArea4);

        jTextArea5.setColumns(50);
        jTextArea5.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jTextArea5.setRows(1);
        jTextArea5.setAutoscrolls(false);
        jScrollPane5.setViewportView(jTextArea5);

        jButton4.setFont(new java.awt.Font("Tunga", 1, 36)); // NOI18N
        jButton4.setText(bundle.getString("project_gui.jButton4.text")); // NOI18N
        jButton4.addActionListener(this);

        jLabel1.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel1.setText(bundle.getString("project_gui.jLabel1.text")); // NOI18N

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel2.setText(bundle.getString("project_gui.jLabel2.text")); // NOI18N

        jTextPane2.setEditable(false);
        jTextPane2.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jScrollPane1.setViewportView(jTextPane2);

        jLabel3.setBackground(new java.awt.Color(51, 255, 255));
        jLabel3.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(153, 0, 0));
        jLabel3.setText(bundle.getString("project_gui.jLabel3.text")); // NOI18N
        jLabel3.setOpaque(true);

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jPanel1Layout.createSequentialGroup()
                .add(0, 395, Short.MAX_VALUE)
                .add(jButton2)
                .add(401, 401, 401))
            .add(jPanel1Layout.createSequentialGroup()
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(49, 49, 49)
                        .add(jScrollPane5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 732, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .add(18, 18, 18)
                        .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 175, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(18, 18, 18)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                            .add(jLabel1)
                            .add(jLabel2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 162, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                        .add(36, 36, 36)
                        .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                            .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 732, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                            .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 732, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(345, 345, 345)
                        .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 320, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel1Layout.createSequentialGroup()
                        .add(303, 303, 303)
                        .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 395, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel1Layout.createSequentialGroup()
                .add(jLabel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 60, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .add(jButton4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 91, Short.MAX_VALUE)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane4, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(70, 70, 70)
                .add(jButton2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(33, 33, 33)
                .add(jScrollPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(121, 121, 121))
        );

        org.jdesktop.layout.GroupLayout jLayeredPane1Layout = new org.jdesktop.layout.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1Layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane1Layout.createSequentialGroup()
                .add(jPanel1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane1.setLayer(jPanel1, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab(bundle.getString("project_gui.jLayeredPane1.TabConstraints.tabTitle"), jLayeredPane1); // NOI18N

        jLayeredPane2.setPreferredSize(new java.awt.Dimension(1024, 672));

        jPanel3.setPreferredSize(new java.awt.Dimension(1024, 730));

        jTextArea6.setColumns(50);
        jTextArea6.setFont(new java.awt.Font("Comic Sans MS", 3, 18)); // NOI18N
        jTextArea6.setRows(1);
        jTextArea6.setAutoscrolls(false);
        jScrollPane7.setViewportView(jTextArea6);

        jButton1.setFont(new java.awt.Font("Tunga", 1, 36)); // NOI18N
        jButton1.setText(bundle.getString("project_gui.jButton1.text")); // NOI18N
        jButton1.addActionListener(this);

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(100);
        jTextArea1.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea1.setRows(1);
        jTextArea1.setAutoscrolls(false);
        jScrollPane2.setViewportView(jTextArea1);

        jTextArea2.setEditable(false);
        jTextArea2.setColumns(100);
        jTextArea2.setFont(new java.awt.Font("Monospaced", 1, 16)); // NOI18N
        jTextArea2.setRows(1);
        jTextArea2.setAutoscrolls(false);
        jScrollPane8.setViewportView(jTextArea2);

        jLabel4.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel4.setText(bundle.getString("project_gui.jLabel4.text")); // NOI18N

        jLabel5.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel5.setText(bundle.getString("project_gui.jLabel5.text")); // NOI18N

        jButton3.setFont(new java.awt.Font("Shruti", 1, 24)); // NOI18N
        jButton3.setText(bundle.getString("project_gui.jButton3.text")); // NOI18N
        jButton3.addActionListener(this);

        jTextPane3.setEditable(false);
        jTextPane3.setFont(new java.awt.Font("Tw Cen MT", 1, 24)); // NOI18N
        jScrollPane9.setViewportView(jTextPane3);

        jLabel6.setBackground(new java.awt.Color(255, 176, 34));
        jLabel6.setFont(new java.awt.Font("Snap ITC", 3, 36)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 153));
        jLabel6.setText(bundle.getString("project_gui.jLabel6.text")); // NOI18N
        jLabel6.setOpaque(true);

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(47, 47, 47)
                .add(jScrollPane7, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 732, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(28, 28, 28)
                .add(jButton1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(50, 50, 50))
            .add(jPanel3Layout.createSequentialGroup()
                .add(19, 19, 19)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .add(32, 32, 32)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .add(jScrollPane8, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 732, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(79, 79, 79))
            .add(jPanel3Layout.createSequentialGroup()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(382, 382, 382)
                        .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 250, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(347, 347, 347)
                        .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 315, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(jPanel3Layout.createSequentialGroup()
                        .add(301, 301, 301)
                        .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 408, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .add(jLabel6, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 61, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane7, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 55, Short.MAX_VALUE)
                    .add(jButton1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .add(92, 92, 92)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jLabel4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(jScrollPane2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(jScrollPane8)
                    .add(jLabel5, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(68, 68, 68)
                .add(jButton3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 70, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(32, 32, 32)
                .add(jScrollPane9, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 64, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(112, Short.MAX_VALUE))
        );

        org.jdesktop.layout.GroupLayout jLayeredPane2Layout = new org.jdesktop.layout.GroupLayout(jLayeredPane2);
        jLayeredPane2.setLayout(jLayeredPane2Layout);
        jLayeredPane2Layout.setHorizontalGroup(
            jLayeredPane2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane2Layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane2Layout.setVerticalGroup(
            jLayeredPane2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jLayeredPane2Layout.createSequentialGroup()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        jLayeredPane2.setLayer(jPanel3, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab(bundle.getString("project_gui.jLayeredPane2.TabConstraints.tabTitle"), jLayeredPane2); // NOI18N

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Monospaced", 1, 14)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText(bundle.getString("project_gui.jTextArea7.text")); // NOI18N
        jScrollPane6.setViewportView(jTextArea7);

        org.jdesktop.layout.GroupLayout jPanel2Layout = new org.jdesktop.layout.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jScrollPane6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 1019, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, jScrollPane6, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
        );

        org.jdesktop.layout.GroupLayout jLayeredPane3Layout = new org.jdesktop.layout.GroupLayout(jLayeredPane3);
        jLayeredPane3.setLayout(jLayeredPane3Layout);
        jLayeredPane3Layout.setHorizontalGroup(
            jLayeredPane3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane3Layout.setVerticalGroup(
            jLayeredPane3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane3.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        jTabbedPane1.addTab(bundle.getString("project_gui.jLayeredPane3.TabConstraints.tabTitle"), jLayeredPane3); // NOI18N

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(jTabbedPane1, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }

    // Code for dispatching events from components to event handlers.

    public void actionPerformed(java.awt.event.ActionEvent evt) {
        if (evt.getSource() == jButton5) {
            project_gui.this.jButton5ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton6) {
            project_gui.this.jButton6ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton7) {
            project_gui.this.jButton7ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton8) {
            project_gui.this.jButton8ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton9) {
            project_gui.this.jButton9ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton10) {
            project_gui.this.jButton10ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton2) {
            project_gui.this.jButton2ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton4) {
            project_gui.this.jButton4ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton1) {
            project_gui.this.jButton1ActionPerformed(evt);
        }
        else if (evt.getSource() == jButton3) {
            project_gui.this.jButton3ActionPerformed(evt);
        }
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        byte[] input;
        BigInteger ext = new BigInteger("txt".getBytes());
        IOException exp = new IOException();
        jTextPane2.setText("ERROR");
        try{
            if(rsa_privatekey_d.equals("") || rsa_publickey_e.equals("") || rsa_privatekey_n.equals("") || rsa_publickey_n.equals(""))
                throw ae;
            File file = new File(jTextArea5.getText());
            String s = file.getName();
            String n="Encrypted.txt";
            if(file==null)
                throw exp;
            //ext = new BigInteger((s).getBytes());
            int i = (s).lastIndexOf('.');
            if (i > 0 &&  i < s.length() - 1){
                n = file.getName().substring(0, i);
                ext = new BigInteger((s.substring(i+1).toLowerCase()).getBytes());
            }
            if(!enc_name.equals(""))
                n=enc_name;
            try{
                File t = new File(enc_path+n+".crypt");
                FileReader rh = new FileReader(t);
                BufferedReader b = new BufferedReader(rh);
                info("File Already Exists\nPlease rename the file\nIn Settings pane");
            }
            catch(FileNotFoundException re){
                try (FileInputStream in = new FileInputStream (file)) {
                    input = new byte [(int)file.length()];
                    in.read(input);
                }
                sha_256 digest = new sha_256();
                byte [] hash = digest.hash(input);
                byte [] hash2 = new byte[33];
                hash2 [0]=0;
                for(int x=1;x<33;x++)
                    hash2[x]=hash[x-1];
                
                byte [] key = key_generate.toByteArray();
                aes_encrption e = new aes_encrption();
                byte [] encrypted = e.encrypt(input, key);
                
                BigInteger prkn = new BigInteger(rsa_privatekey_n);
                BigInteger prkd = new BigInteger(rsa_privatekey_d);
                BigInteger pukn = new BigInteger(rsa_publickey_n);
                BigInteger puke = new BigInteger(rsa_publickey_e);
                BigInteger inp = new BigInteger(hash2);
                rsa_enc_dec rsa = new rsa_enc_dec();
                byte [] sign = rsa.encrypt_decrypt(inp, prkd, prkn);
                BigInteger keygen = new BigInteger(key);
                byte [] enckey = rsa.encrypt_decrypt(keygen, puke, pukn);
                byte [] enext = rsa.encrypt_decrypt(ext, puke, pukn);
                byte [] delim = {'$','|',']','['};
                file = new File(enc_path+n+".crypt");
                
                try (FileOutputStream out = new FileOutputStream (file)) {
                    out.write(encrypted);
                    out.write(delim);
                    out.write(enckey);
                    out.write(delim);
                    out.write(sign);
                    out.write(delim);
                    out.write(enext);
                }
               jTextPane2.setText("Encrypted Successfully.");
               info("Encrypted File :\n"+enc_path+n+".crypt");
            }
        }
        catch(ArithmeticException e){
            jTextPane2.setText("MISSING KEYS.");
            info("Please Provide Keys Path\nIn Settings Correctly.");
        }
        catch(IOException e){
            jTextPane2.setText("ERROR OCCURED. "+e);
            info("File cannot be select because :\n"+e);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        
        try{
            if(rsa_privatekey_d.equals("") || rsa_publickey_e.equals("") || rsa_privatekey_n.equals("") || rsa_publickey_n.equals(""))
                throw ae;
            File file = null;
            JFileChooser fc = new JFileChooser();
            FileFilter filter = new FileNameExtensionFilter(".txt","txt");
            fc.setFileFilter(filter);
            int returnVal = fc.showOpenDialog(this);
            if (returnVal == JFileChooser.APPROVE_OPTION)
                file = fc.getSelectedFile();
            if(file != null)
                jTextArea5.setText(file.getPath());
            FileInputStream gh = new FileInputStream(file);
            gh.close();
            jTextPane2.setText("File Selected");
        }
        catch(ArithmeticException e){
            jTextPane2.setText("Keys not found");
            info("Please Provide Keys Path\nIn Settings Correctly.");
        }
        catch(IOException e){
            jTextPane2.setText("ERROR OCCURED");
            info("File cannot be select because :\n"+e);
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        try{
            if(rsa_privatekey_d.equals("") || rsa_publickey_e.equals("") || rsa_privatekey_n.equals("")||rsa_publickey_n.equals(""))
                throw ae;
            File file1=null;
            String dir = System.getProperty("user.dir");
                JFileChooser fc = new JFileChooser(dir);
                FileFilter filter = new FileNameExtensionFilter(".crypt","crypt");
                fc.setFileFilter(filter);
                fc.setAcceptAllFileFilterUsed(false);
                int returnVal = fc.showOpenDialog(this);
                if (returnVal == JFileChooser.APPROVE_OPTION)
                    file1 = fc.getSelectedFile();
                else
                    fc.removeAll();
            if(file1!=null)
                jTextArea6.setText(file1.getPath());
            FileInputStream gh = new FileInputStream(file1);
            gh.close();
            jTextPane3.setText("File Selected");
        }
        catch(ArithmeticException e){
            jTextPane3.setText("Keys not found");
            info("Please Provide Keys Path\nIn Settings Correctly.");
        }
        catch(IOException e){
            jTextPane3.setText("File cannot be selected "+e);
            info("File cannot be select because :\n"+e);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        byte [] enc1;
        int [] delim1 = new int [3];
        IOException exp = new IOException();
        int a=0,b=0,c=0,d=0;
        String n="Decrypted.txt";
        File file1;
        try{
            if(rsa_privatekey_d.equals("") || rsa_publickey_e.equals("") || rsa_privatekey_n.equals("") || rsa_publickey_n.equals(""))
                throw ae;
            file1 = new File(jTextArea6.getText());
            if(file1 == null)
                throw exp;
            String s = file1.getName();
            int i = (s).lastIndexOf('.');
            if (i > 0 &&  i < s.length() - 1)
                n = file1.getName().substring(0, i);
            
            try{
                File t = new File(enc_path+n+".crypt");
                FileReader rh = new FileReader(t);
                BufferedReader br = new BufferedReader(rh);
                info("File Already Exists\nPlease rename the file\nIn settings pane");
            }
            catch(FileNotFoundException re){
                try (FileInputStream in = new FileInputStream (file1)) {
                    enc1 = new byte [(int)file1.length()];
                    in.read(enc1);
                }
                for(int x=0;x<enc1.length-4;x++)
                {
                    if(enc1[x]=='$'&&enc1[x+1]=='|'&&enc1[x+2]==']'&&enc1[x+3]=='[')
                        delim1[a++]=x;
                }
                
                byte [] aes1 = new byte [delim1[0]];
                byte [] rsa_key1 = new byte [delim1[1]-delim1[0]-4];
                byte [] rsa_hash1 = new byte [delim1[2]-delim1[1]-4];
                byte [] rsa_ext = new byte [enc1.length-delim1[2]-4];
                
                for(int x=0;x<enc1.length;x++)
                {
                    if(x<delim1[0])
                        aes1[x]=enc1[x];
                    else if(x>=(delim1[0]+4)&&x<delim1[1])
                        rsa_key1[b++]=enc1[x];
                    else if (x>=(delim1[1]+4)&&x<delim1[2])
                        rsa_hash1[c++]=enc1[x];
                    else if (x>=(delim1[2]+4))
                        rsa_ext[d++] = enc1[x];
                }
                
                BigInteger rk = new BigInteger(rsa_key1);
                BigInteger hs = new BigInteger(rsa_hash1);
                BigInteger ex = new BigInteger(rsa_ext);
                BigInteger prkeyd = new BigInteger(rsa_privatekey_d);
                BigInteger prkeyn = new BigInteger(rsa_privatekey_n);
                BigInteger pukeye = new BigInteger(rsa_publickey_e);
                BigInteger pukeyn = new BigInteger(rsa_publickey_n);
                rsa_enc_dec r1 = new rsa_enc_dec();
                byte [] key1 = r1.encrypt_decrypt(rk, prkeyd, prkeyn);
                byte [] ext1 = r1.encrypt_decrypt(ex, prkeyd, prkeyn);
                byte [] hash1 = r1.encrypt_decrypt(hs, pukeye, pukeyn);
            
                byte [] hash3 = new byte [hash1.length-1];
            
                for (int x=0; x<hash1.length-1;x++)
                    hash3[x]=hash1[x+1];
                
                aes_decryption ad = new aes_decryption();
                byte [] dec = ad.decrypt(aes1, key1);
                int y=0;
                for(int x=dec.length-1;x>=0;x--)
                    if(dec[x]==0)
                        y++;
                    else
                        break;
                final byte [] dec1 = new byte [dec.length-y];
                System.arraycopy(dec, 0, dec1, 0, dec1.length);
                //dec1[dec1.length-1]=0;
                sha_256 sha = new sha_256();
                byte[] hash_value = sha.hash(dec1);
                int flag =0;
                if(hash1[0]==0)
                    for(int x=0;x<hash_value.length;x++)
                    {
                        if(hash3[x]!=hash_value[x])
                        {
                            flag=1;
                            break;
                        }
                    }
                else
                    for(int x=0;x<hash_value.length;x++)
                    {
                        if(hash1[x]!=hash_value[x])
                        {
                            flag=1;
                            break;
                        }
                    }
                String ext2 = "";
                for(int x=0;x<ext1.length;x++)
                    ext2+=(char)ext1[x];
                if(!dec_name.equals(""))
                    n=dec_name;
                
                if(flag==0)
                {
                    try (FileOutputStream out = new FileOutputStream(dec_path+n+"."+ext2)) {
                    out.write(dec1);
                }
                jTextPane3.setText("File AUTHENTIC And Decrypted");
                info("Decrypted File :\ndec_path"+n+"."+ext2);
                }
                else
                {
                    final JFrame f = new JFrame ("WARNING !!!");
                    f.setSize(300,300);
                    f.setVisible(true);
                    JButton con = new JButton("Press to CONTINUE\nCancel to discard");
                    f.getContentPane().add(con);
                    final String n1=n, ext3=ext2;
                    con.addActionListener(new ActionListener() {
                        @Override
                        public void actionPerformed(ActionEvent ae)
                        {
                            try (FileOutputStream out = new FileOutputStream(n1+"."+ext3)) {
                                out.write(dec1);
                            } catch (IOException ex) {
                                Logger.getLogger(project_gui.class.getName()).log(Level.SEVERE, null, ex);
                            }
                            f.dispose();
                    }});
                    jTextPane3.setText("File NOT AUTHENTIC And Decrypted");
                    info("Decrypted File :\ndec_path"+n+"."+ext2);
                }
            }
        }
        catch(ArithmeticException e)
        {
            jTextPane3.setText("MISSING KEYS");
            info("Please Provide Keys Path\nIn Settings Correctly.");
        }
        catch(IOException e)
        {
            jTextPane3.setText("Error Occured. "+e);
            info("File cannot be select because :\n"+e);
        }

    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        choose(jTextArea13);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        choose(jTextArea8);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        choose(jTextArea11);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        choose(jTextArea12);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        jTextArea13.setText(jTextArea12.getText());
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
            // TODO add your handling code here:
        FileNotFoundException ex = new FileNotFoundException();
        try (PrintWriter fw = new PrintWriter("settings.txt")) {
            if(!(jTextArea8.getText().equals("")))
                fw.println(jTextArea8.getText());
            else
            {
                fw.close();
                throw ex;
            }
            if(!jTextArea9.getText().equals(""))
                fw.println(jTextArea9.getText());
            else
                fw.println();
            if(!jTextArea11.getText().equals(""))
                fw.println(jTextArea11.getText());
            else
            {
                fw.close();
                throw ex;
            }
            if(!jTextArea10.getText().equals(""))
                fw.println(jTextArea10.getText());
            else
                fw.println();
            if(!jTextArea12.getText().equals(""))
                fw.println(jTextArea12.getText());
            else
            {
                fw.close();
                throw ex;
            }
            if(!jTextArea13.getText().equals(""))
                fw.println(jTextArea13.getText());
            else
            {
                fw.close();
                throw ex;
            }
            fw.close();
            initialise();
            info("SETTINGS APPLIED");
        }
        catch(FileNotFoundException er){
            info("Please fill up the mandatory boxes\ncorrectly.");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void choose(javax.swing.JTextArea t){
        JFileChooser fc = new JFileChooser();
        File file1 = null;
        fc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int returnVal = fc.showOpenDialog(this);
        if (returnVal == JFileChooser.APPROVE_OPTION)
        {
            file1 = fc.getSelectedFile();
        }
        else
            fc.removeAll();
        if(file1 != null)
            t.setText(file1.getPath()+"\\");

    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(project_gui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                    new project_gui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton10;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton3;
    javax.swing.JButton jButton4;
    javax.swing.JButton jButton5;
    javax.swing.JButton jButton6;
    javax.swing.JButton jButton7;
    javax.swing.JButton jButton8;
    javax.swing.JButton jButton9;
    javax.swing.JSeparator jSeparator3;
    javax.swing.JTextArea jTextArea1;
    javax.swing.JTextArea jTextArea10;
    javax.swing.JTextArea jTextArea11;
    javax.swing.JTextArea jTextArea12;
    javax.swing.JTextArea jTextArea13;
    javax.swing.JTextArea jTextArea2;
    javax.swing.JTextArea jTextArea3;
    javax.swing.JTextArea jTextArea4;
    javax.swing.JTextArea jTextArea5;
    javax.swing.JTextArea jTextArea6;
    javax.swing.JTextArea jTextArea8;
    javax.swing.JTextArea jTextArea9;
    javax.swing.JTextPane jTextPane2;
    javax.swing.JTextPane jTextPane3;
    // End of variables declaration//GEN-END:variables
}